server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tripverse
#    url: jdbc:mysql://tripverse-db.cnagqmcc6foj.ap-northeast-2.rds.amazonaws.com:3306/tripverse
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        open-in-view: false
        globally_quoted_identifiers: true

  data:
    redis:
      host: localhost
      port: 6379

  logging:
    level:
      org.springframework.cache: trace

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB

  jackson:
    serialization:
      write-dates-as-timestamps: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo



jwt:
  secret: ${JWT_SECRET}
  token-validity-in-seconds: 86400

cloud:
  aws:
    s3:
      bucket: tripverse-uploaded-files
    credentials:
      access-key: ${AWS_CREDENTIALS_ACCESS_KEY}
      secret-key: ${AWS_CREDENTIALS_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

gcp:
  project-id: tripverse-456512
  location: us-central1
  gemini-api-url: https://us-central1-aiplatform.googleapis.com/v1/projects/tripverse-456512/locations/us-central1/publishers/google/models/gemini-2.5-flash:generateContent
  service-account-key-path: classpath:service-account.json